return PlaceObj('ModDef', {
	'title', "Sir Ni's Hat of Tricks",
	'description', "[h1]Sir Ni's Hat of Tricks[/h1]\n[h3]This mod uses part of the code of the old [url=https://steamcommunity.com/sharedfiles/filedetails/?id=3007587788] Custom Settings [/url]mod[/h3]\nIf you are using options to increase the number of enemies, consider using \"Vanilla Battles Enhanced\" as well because that mod increase the size of some grids in the map to support more enemies than vanilla (to avoid softlocks).\n\n[h3][i]Features:[/i][/h3]\n[list]\n\n    [*][b]Merc Inventory Size[/b]\n    Increases the inventory size on all mercenaries to either max (24 slots), or by a configurable multiplier- or number applied to each mercenary.\n\n    [*][b]Sector Inventory Sorting[/b]\n    Modifies the inventory UI to include a toggle for sorting the sector inventory.\n	Shortcut -> \"Y\"\n\n    [*][b]Merc Max Level[/b]\n    Maximum level of player mercenaries.\n\n    [*][b]Merc Squad Max People[/b]\n    Maximum number of members in each player squad.\n\n    [*][b]Max Hired Mercs[/b]\n    Maximum number of mercenaries that can be hired at the same time.\n\n    [*][b]Sector Max Militia[/b]\n    Maximum number of militia members that can be trained in each sector.\n	\n	[*][b]Enemy Squad Size Multiplier[/b]\n	Multiplies the number of units in enemy squads by a set factor. It only applies to squads and not to units manually placed on the map. When this setting is active at the start of a new game, it will adjust the number of units in squads that initially spawn in various sectors.\n\n	[*][b]Base Drop Chance[/b]\n	Enemies can drop all their equiped gear. Only in combat mode. Don't ask me to make available for auto-resolve. I won't do it. Changes the drop probability of all items, I wont make it individual.\n\n	[*][b]JA2Perks[/b]\n	Adds the following: Igor (\"AutoWeapons\") Grunty (\"NightOps\") Hitman (\"Throwing\") Ice (\"Teacher\") Ivan (\"HeavyWeaponsTraining\") Len (\"AutoWeapons\") MD (\"MartialArts\" )Grizzly (\"MeleeTraining\") Raven (\"NightOps\") Red (\"Teaching\") Scope (\"Teaching\") Scully (\"Throwing\") Sidney (\"Ambidextrous\") and Nationalities = \"NewZealand\" Thor (\"MeleeTraining\") Wolf (\"NightOps\")\n\n	[*][b]IncreaseStacks[/b]\n	Increase Stacks for stackable items. All.\n\n	[*][b]EnhancedSquadBag[/b]\n	Adds several items to squad bag(quest items included, except for Diesel because it triggers a radio conversation), as side effect make wirecutter, lockpick and crowbar unbreakeable. ¯\\_(ツ)_/¯\n\n	[*][b]No more MIA[/b]\n	Returns MIA mercs to Available status. It may take a few days until day return. It works only for MIA, I won't bring the back the dead, I am not your personal Jesus.	\n\n	[*][b]Skip Setpiece[/b]\n	Skip setpiece awaress sequence, yes the annoying one.\n\n	[*][b]Control Groups Shortcut[/b]\n	You can save the selected group pressing ALT+1 to 9 and recall with CTRL+1 to 9\n\n	[*][b]Shush[/b]\n	Drastically reduces the repetition of some voice responses.\n\n	[*][b]Respec Perk Points[/b]\n	Select a merc and pres CTRL + ALT + R to respec 1 perk point.\n	\n	[*][b]No Dislikes[/b]\n	Nobody dislikes nobody.\n	\n	[*][b]All Learn to Like[/b]\n	All mercs are inserted in all mercs table Learn to Like\n		\n[/list]\n\nWhen you create a game, a number of sector NPCs and initial squads are generated. The Base Drop Chance settings won't alter units and squads that have already spawned, but it will influence anything generated while the setting is enabled.\n\nAs you continue playing the game, new squads will be created, which occurs quite quickly, eliminating the need to start a new save game. However, even later in the game, when facing the initial squads, they will drop fewer items.\n\nFor a comprehensive list of which item belongs to each type, please refer to:\n[url=https://steamcommunity.com/workshop/filedetails/discussion/3007587788/3809533247342267557/]Item Types[/url]\nhe editor is found in the Mod Menu under [b]Options > Advanced Settings[/b].\n[hr][/hr]\n[h3][i]Why did you excluded the advanced custom settings?[/i][/h3]\n	[list]\n	[*][b]There is not a place to play with cons.[/b]\n	[*][b]If you want to manipulate those kinda of things you should consider become a modder.[/b]\n	[/list]\n[h3][i]Why did you exclude some of the Custom Settings Options?[/i][/h3]\nTo be quite frankly because many were redundant  or useless nowadays, also I don't understand the obsession with show CTH or pause the damn game, every fuckin mod.\n\n[h3][url=https://ko-fi.com/sirni] You can support me here, or just see my funny face.[/url][/h3]",
	'image', "Mod/BagOfTricks/Images/459b82fb238652dc0f209bc599203a1a.jpg",
	'last_changes', "- added NoDislikes option\n- added allLearnToLikeOptions",
	'dependencies', {
		PlaceObj('ModDependency', {
			'id', "JA3_CommonLib",
			'title', "JA3_CommonLib",
			'version_major', 1,
			'version_minor', 1,
		}),
	},
	'id', "BagOfTricks",
	'author', "Sir Ni",
	'version_major', 1,
	'version_minor', 1,
	'version', 262,
	'lua_revision', 233360,
	'saved_with_revision', 350233,
	'code', {
		"Code/Shush.lua",
		"Code/NoDislikes.lua",
		"Code/AllLearnToLike.lua",
		"Code/Script1.lua",
		"Code/Script2.lua",
		"Code/ChangePerks.lua",
		"Code/ControlGroup.lua",
		"Code/IncreaseStacks.lua",
		"Code/EnhancedSquadBag.lua",
		"Code/NoMoreMIA.lua",
		"Code/stackChange.lua",
		"Code/DropItMF.lua",
		"Code/Utils.lua",
		"Code/Script.lua",
		"Code/UI_Modifications.lua",
		"Code/ModMenu.lua",
		"Code/AdvancedSettings.lua",
		"Code/InventorySorting.lua",
		"Code/Dev.lua",
		"Code/SNSkipSetPiece.lua",
	},
	'default_options', {
		AllLearnToLike = false,
		Cheats = false,
		ControlGroupControls = false,
		EnhancedSquadBag = false,
		IncreaseStacks = false,
		JA2Perks = false,
		LOOT_DROP_PROBABILITY = "Default",
		NoDislikes = false,
		NoMoreMIA = false,
		Respec = false,
		SNSkipSetPiece = false,
		Shush = false,
		idCS_EnemySquadSizeMultiplier = "Default (1)",
		idCS_InventorySorting = false,
		idCS_MaxHiredMercs = "Default (15)",
		idCS_MercInventorySizeMode = "Disabled",
		idCS_MercMaxLevel = "Default (10)",
		idCS_MercSquadMaxPeople = "Default (6)",
		idCS_SatelliteSectorMaxMilitia = "Default (8)",
	},
	'has_data', true,
	'saved', 1728746982,
	'code_hash', -3171628949608225026,
	'affected_resources', {
		PlaceObj('ModResourcePreset', {
			'Class', "XTemplate",
			'Id', "SNHoTShortcuts",
			'ClassDisplayName', "UI Template (XTemplate)",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "XTemplate",
			'Id', "ControlGroups",
			'ClassDisplayName', "UI Template (XTemplate)",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "XTemplate",
			'Id', "Inventory",
			'ClassDisplayName', "UI Template (XTemplate)",
		}),
	},
	'steam_id', "3255590356",
	'TagGameSettings', true,
})