local InventoryItemCompositeDef = {
	"_12gauge_Breacher",
	"_12gauge_Buckshot",
	"_12gauge_Flechette",
	"_12gauge_Saltshot",
	"_40mmFlashbangGrenade",
	"_40mmFragGrenade",
	"_44CAL_AP",
	"_44CAL_Basic",
	"_44CAL_HP",
	"_44CAL_Match",
	"_44CAL_Shock",
	"_50BMG_Basic",
	"_50BMG_HE",
	"_50BMG_Incendiary",
	"_50BMG_SLAP",
	"_556_AP",
	"_556_Basic",
	"_556_HP",
	"_556_Match",
	"_556_Tracer",
	"_762NATO_AP",
	"_762NATO_Basic",
	"_762NATO_HP",
	"_762NATO_Match",
	"_762NATO_Tracer",
	"_762WP_AP",
	"_762WP_Basic",
	"_762WP_HP",
	"_762WP_Match",
	"_762WP_Tracer",
	"_9mm_AP",
	"_9mm_Basic",
	"_9mm_HP",
	"_9mm_Match",
	"_9mm_Shock",
	"_9mm_Subsonic",
	"_9mm_Tracer",
--	"AA12",
--	"AK47",
--	"AK74",
--	"AKSU",
--	"AR15",
--	"AUG",
--	"Auto5",
--	"Auto5_quest",
--	"BarretM82",
--	"Bereta92",
	"BigDiamond",
	"BlackPowder",
--	"BrowningM2HMG",
	"C4",
--	"CamoArmor_Light",
--	"CamoArmor_Medium",
--	"Car",
	"ChippedSapphire",
--	"Coin",
--	"ColtAnaconda",
--	"ColtPeacemaker",
	"CombatStim",
	"Combination_BalancingWeight",
	"Combination_CeramicPlates",
	"Combination_Detonator_Proximity",
	"Combination_Detonator_Remote",
	"Combination_Detonator_Time",
	"Combination_Sharpener",
	"Combination_WeavePadding",
	"ConcussiveGrenade",
	"Cookie",
--	"CrocodileHide",
--	"CrocodileJaws",
--	"Crowbar",
--	"CustomPDA",
--	"DebugAuto",
--	"DesertEagle",
--	"Detonator",
	"DiamondBriefcase",
--	"DiamondNecklace",
--	"Diesel",
--	"DoubleBarrelShotgun",
--	"DragunovSVD",
--	"EndlessKnives",
--	"FAMAS",
	"FineSteelPipe",
--	"FirstAidKit",
--	"FlakArmor",
--	"FlakArmor_CeramicPlates",
--	"FlakArmor_WeavePadding",
--	"FlakLeggings",
--	"FlakLeggings_WeavePadding",
--	"FlakVest",
--	"FlakVest_CeramicPlates",
--	"FlakVest_Test",
--	"FlakVest_WeavePadding",
	"FlareAmmo",
--	"FlareHandgun",
	"FlareStick",
--	"FNFAL",
--	"FNMinimi",
	"FragGrenade",
--	"FuelTank",
--	"G36",
--	"Galil",
--	"Galil_FlagHill",
--	"GasMask",
--	"Gewehr98",
--	"Glock18",
	"GlowStick",
	"GoldBar",
--	"GoldenGun",
--	"GoldenWatch",
--	"GutHookKnife",
	"HE_Grenade",
--	"HeavyArmorChestplate",
--	"HeavyArmorChestplate_CeramicPlates",
--	"HeavyArmorChestplate_WeavePadding",
--	"HeavyArmorHelmet",
--	"HeavyArmorHelmet_WeavePadding",
--	"HeavyArmorLeggings",
--	"HeavyArmorLeggings_WeavePadding",
--	"HeavyArmorTorso",
--	"HeavyArmorTorso_CeramicPlates",
--	"HeavyArmorTorso_WeavePadding",
	"HerbalMedicine",
--	"HiPower",
--	"HK21",
--	"HyenaJaws",
--	"Infected_HardenedSkin",
--	"IvanUshanka",
--	"KevlarChestplate",
--	"KevlarChestplate_CeramicPlates",
--	"KevlarChestplate_WeavePadding",
--	"KevlarHelmet",
--	"KevlarHelmet_WeavePadding",
--	"KevlarLeggings",
--	"KevlarLeggings_WeavePadding",
--	"KevlarVest",
--	"KevlarVest_CeramicPlates",
--	"KevlarVest_WeavePadding",
	"Knife",
	"Knife_Balanced",
	"Knife_Sharpened",
--	"LightHelmet",
--	"LightHelmet_WeavePadding",
--	"LionRoar",
--	"Lockpick",
--	"M14SAW",
--	"M16A2",
--	"M24Sniper",
--	"M41Shotgun",
--	"M4Commando",
--	"Machete",
--	"Machete_Balanced",
--	"Machete_Crafted",
--	"Machete_Sharpened",
--	"MedicalReport",
--	"Medkit",
	"Meds",
	"MetaviraShot",
--	"MG42",
--	"MGL",
	"Microchip",
--	"MissingItem",
	"Molotov",
	"MoneyBag",
--	"Moped",
--	"MortarInventoryItem",
	"MortarShell_Gas",
	"MortarShell_HE",
	"MortarShell_Smoke",
--	"MP40",
--	"MP5",
--	"MP5K",
--	"NailsLeatherVest",
--	"NightVisionGoggles",
	"OpticalLens",
--	"PaBaggzWill",
--	"Pamphlets",
--	"Pamphlets_LysRouge",
	"Parts",
--	"Personal_Vicki_CustomTools",
	"PETN",
--	"PickupTruck",
--	"PierreMachete",
	"PipeBomb",
--	"PlasmaGun_Crowbar",
--	"PostApoHelmet",
--	"PowerGenerator",
--	"PowerGenerator_Military",
	"ProximityC4",
	"ProximityPETN",
	"ProximityTNT",
--	"PSG1",
	"RemoteC4",
	"RemotePETN",
	"RemoteTNT",
--	"RPG7",
--	"RPK74",
--	"ShamanHelmet",
--	"ShamanLeggings",
--	"ShamanTorso",
	"ShapedCharge",
	"SkillMag_Agility",
	"SkillMag_Dexterity",
	"SkillMag_Explosives",
	"SkillMag_Health",
	"SkillMag_Leadership",
	"SkillMag_Marksmanship",
	"SkillMag_Mechanical",
	"SkillMag_Medical",
	"SkillMag_Strength",
	"SkillMag_Wisdom",
	"SmokeGrenade",
--	"SteroidPunchGrenade",
--	"Super_HE_Grenade",
	"TearGasGrenade",
--	"Ted",
--	"TexRevolver",
--	"TheGreenDiamond",
--	"TheThing",
	"TimedC4",
	"TimedPETN",
	"TimedTNT",
	"TinyDiamonds",
	"TNT",
	"ToxicGasGrenade",
	"TreasureFigurine",
	"TreasureGoldenDog",
	"TreasureIdol",
	"TreasureMask",
	"TreasureTablet",
--	"Trophy",
--	"Unarmed",
--	"Unarmed_Infected",
--	"UnderslungGrenadeLauncher",
--	"US_Passport",
--	"UZI",
--	"VirusSample",
	"Warhead_Frag",
--	"WeirdosMap",
--	"Wig",
--	"Winchester_Quest",
--	"Winchester1894",
--	"Wirecutter",
--	"WorkerDiary",
--	"WriterDiary",
--	"WriterLetter",
--	"WriterPage",
	"Combination_Kompositum58",

}

local function IncreaseStacks(stacks)
	for _, obj in ipairs(InventoryItemCompositeDef) do
		_G[obj].MaxStacks = stacks
	end
end

function OnMsg.ApplyModOptions()
	if CurrentModOptions["IncreaseStacks"] == true then
		IncreaseStacks(10000)
	end
end

function InventoryStack:GetItemSlotUI()
  return T({0, "<style InventoryItemsCount><cur></style>", cur = self.Amount})
end

-- UI FIX 2
function TFormat.bullets(context_obj, bullets, max, icon)
  icon = icon or "<image UI/Icons/Rollover/ammo_placeholder 1400>"
  bullets = bullets or GetBulletCount(context_obj)
  if not bullets then
    return T(994336406701, "<image UI/Icons/Hud/ammo_infinite>")
  end
  local max = max or context_obj and context_obj.MagazineSize --or context_obj.MaxStacks
  local text = bullets == 0 and "<error><bullets></error>" or "<bullets>"
  if not max then
    return T({
      370913997359,
      text,
      bullets = bullets,
      icon = icon
    })
  else
    text = text .. "/<style InventoryItemsCountMax><max></style>"
    return T({
      text,
      bullets = bullets,
      max = max or 0,
      icon = icon
    })
  end
end